"""
Domain entities - Pure data classes without external dependencies.

This module defines the core data structures used throughout the text2midi system.
All entities are framework-agnostic and contain no ML/API dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import List
from uuid import uuid4

# Semantic type aliases for clarity (Python 3.12+)
type TokenId = int
type MidiBytes = bytes
type PromptText = str


@dataclass(frozen=True)
class Intent:
    """
    Represents the user's creative intent in natural language.

    This is the input to the system - what the user wants to generate.
    Examples: "A sunrise at the beach", "A melancholic piano melody".

    Attributes:
        id: Unique identifier for tracking and logging.
        text: The natural language description of the desired musical output.
        timestamp: When this intent was created (UTC, auto-generated).
    """

    text: PromptText
    id: str = field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class GenerationProfile:
    """
    Configuration for the generation search and evaluation process.

    Contains both search parameters (controlling how tokens are generated)
    and reward weights (controlling how candidates are scored).

    Attributes:
        token_batch_size: Number of tokens to generate per step. Must be >= 1.
        num_beams: Number of parallel generation branches (beam search). Must be >= 1.
        top_k: Number of top candidates to consider at each step. Must be >= 1.
        max_tokens: Maximum total tokens to generate. Must be >= 1.
        clap_weight: Weight for CLAP-based audio-text similarity reward.
        key_weight: Weight for music theory key consistency reward.
        note_weight: Weight for note distribution/plausibility reward.

    Raises:
        ValueError: If any parameter is invalid (negative, zero, or weights don't sum to ~1.0).
    """

    # Search parameters
    token_batch_size: int = 500
    num_beams: int = 5
    top_k: int = 2
    max_tokens: int = 2000
    random_seed: int | None = None

    # Reward weights
    clap_weight: float = 0.17
    key_weight: float = 0.42
    note_weight: float = 0.41

    def __post_init__(self) -> None:
        """Validate all parameters after initialization."""
        # Validate search parameters
        if self.token_batch_size < 1:
            raise ValueError(
                f"token_batch_size must be >= 1, got {self.token_batch_size}"
            )
        if self.num_beams < 1:
            raise ValueError(f"num_beams must be >= 1, got {self.num_beams}")
        if self.top_k < 1:
            raise ValueError(f"top_k must be >= 1, got {self.top_k}")
        if self.max_tokens < 1:
            raise ValueError(f"max_tokens must be >= 1, got {self.max_tokens}")

        # Validate reward weights
        if any(w < 0 for w in (self.clap_weight, self.key_weight, self.note_weight)):
            raise ValueError("Reward weights must be non-negative")

        weight_sum = self.clap_weight + self.key_weight + self.note_weight
        if not (0.99 <= weight_sum <= 1.01):
            raise ValueError(
                f"Reward weights must sum to ~1.0, got {weight_sum:.3f} "
                f"(clap={self.clap_weight}, key={self.key_weight}, note={self.note_weight})"
            )


@dataclass(slots=True)
class MidiSequence:
    """
    Represents an in-progress generation branch for beam search.

    A MidiSequence is a candidate being explored during beam search.
    It tracks the technical prompt used, tokens generated so far,
    and the accumulated reward score.

    Implements comparison by reward for natural sorting in beam search.
    Uses slots=True for memory efficiency (high-cardinality objects).

    Attributes:
        technical_prompt: The structured prompt generated by the LLM
            that guides the MIDI token generation.
        tokens: List of MIDI tokens generated up to this point.
        reward: The cumulative reward score for this sequence.
            Set after evaluation, should not be modified during a step.
    """

    technical_prompt: PromptText
    tokens: List[TokenId] = field(default_factory=list)
    reward: float = 0.0

    def __lt__(self, other: MidiSequence) -> bool:
        """Compare by reward for sorting (higher reward = 'greater')."""
        return self.reward < other.reward

    def __le__(self, other: MidiSequence) -> bool:
        return self.reward <= other.reward

    def __gt__(self, other: MidiSequence) -> bool:
        return self.reward > other.reward

    def __ge__(self, other: MidiSequence) -> bool:
        return self.reward >= other.reward

    def copy(self) -> MidiSequence:
        """Create a shallow copy with a new tokens list (for beam branching)."""
        return MidiSequence(
            technical_prompt=self.technical_prompt,
            tokens=list(self.tokens),  # New list, same tokens
            reward=self.reward,
        )


# Configuration for CLAP evaluation prompt source
class ClapPromptSource:
    """
    Determines which text to use for CLAP audio-text similarity evaluation.

    Allows easy switching between:
    - TECHNICAL: Use the LLM-generated structured prompt (more precise)
    - ORIGINAL: Use the user's original intent text (more natural)

    Usage in Evaluator implementation:
        prompt = sequence.technical_prompt if source == ClapPromptSource.TECHNICAL else intent.text
    """

    TECHNICAL: str = "technical"
    ORIGINAL: str = "original"

    @classmethod
    def is_valid(cls, value: str) -> bool:
        return value in (cls.TECHNICAL, cls.ORIGINAL)
